---
 - hosts: webserver
   user: sonny


   tasks:
   - name: install some tools
     apt:
       update_cache=yes
       state=latest
       name={{item}}
     with_items:
     - git
     - sudo
     - wget
